main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('add_todo/', views.add_todo, name='add_todo'),
    path('delete_todo/<int:todo_id>/', views.delete_todo, ),
]

to_do_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    added_date = models.DateTimeField()
    text = models.CharField(max_length=200)

    # def __str__(self):
    #     # return self.text
    #     return '{}'.format(self.text)

main/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils import timezone
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from .models import Todo
# Create your views here.
def home(request):
    # todo_items = Todo.objects.all().order_by('added_date')
    # return render(request, 'outside/index.html', {'todo_items': todo_items})
    return render(request, 'outside/index.html', {'todo_items': Todo.objects.all().order_by('-added_date')[:5]})

@csrf_exempt
def add_todo(request):  # form => only logic and HttpResponseRedirect
    print(request.POST)
    # return HttpResponse('hi %s' % request.POST['todo'])
    # return HttpResponse('{}'.format('Add to do:\t%s' % request.POST['todo']))
    # return HttpResponse('Add to do:\t{}'.format(request.POST['todo']))

    if request.POST['todo'] == '':
        return render(request, 'outside/index.html', {'error_message': "todo field can't be blank. Please fill out."})

    # added_date = timezone.now()
    # todo = request.POST['todo']
    # print(added_date, todo)

    # Todo.objects.create(added_date=added_date, text=todo)
    create_obj = Todo.objects.create(added_date=timezone.now(), text=request.POST['todo'])

    print(create_obj, '\n', create_obj.id, '\n', Todo.objects.all().count())

    # return render(request, 'outside/index.html', {'todo_items': Todo.objects.all()})
    return HttpResponseRedirect('/')

    # return HttpResponseRedirect('')
    #  #call again url => localhost:8000/add_todo and
    # get error MultiValueDictKeyError at /add_todo/    'todo'


def delete_todo(request, todo_id):
    Todo.objects.get(id=todo_id).delete()
    return HttpResponseRedirect("/")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do App</title>

    {% comment %} {% load static %} {% endcomment %}
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>

</head>
<body>


<nav class="navbar navbar-dark bg-dark">
    <a href="" class="navbar-brand">To Do App</a>
</nav>

<div class="container">
    {% block content %} {% endblock %}
</div>



</body>
</html>

templates/outside/index.html
{% extends "base.html" %}


{% block content %}

{% comment %} {% if error_message %}{{ error_message }}{% endif %} {% endcomment %}
{{ error_message }}

<div class="row mt-4">
    <div class="col">

<h2>Add Item</h2>

<form action="{% url 'main:add_todo' %}" method='post' class="form-inlne">
{% csrf_token %}

    <input type="text" name="todo" id="" class="form-control mb-2 mr-sm-2" placeholder="Type Here . . .">

    <button type="submit" class="btn btn-primary mb-2">Submit</button>
</form>

    </div col>
</div row>


<div class="row mt-4">
    <div class="col">
    
<ul class="list-group">
{% for todo_item in todo_items %}
    <li class="list-group-item">{{ todo_item.text }}
    
    <form action="delete_todo/{{ todo_item.id }}/" method='post' class="float-right">
    {% csrf_token %}
        {{todo_item.added_date}}<button class="ml-5 btn btn-danger btn-sm">Delete</button>
    </form>
    
    </li>

{% endfor %}
</ul>

    </div col>
</div row>

{% endblock content %}